

import java.sql.*;
import java.util.Calendar;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Booking.java
 *
 * Created on Jan 25, 2011, 11:22:08 PM
 */

/**
 *
 * @author Administrator
 */
public class Booking extends javax.swing.JFrame {
int stayTime;
    int aMonth,dMonth;
    int aDay;
    int dDay;
    int aYear;
    int dYear;
    /** Creates new form Booking */
    public Booking() {
        initComponents();
         BookingDetailsPart2Panel.setVisible(false);
         EnterBookingDetailsPanel.setVisible(true);
         String m ="0";
        for(int i=1; i<=12; i++)
        {
           if(i>9)
              m="";
           Month.addItem(m+ i);
           Month1.addItem(m+ i);
        }
        ContinueBtn.setVisible(false);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EnterBookingDetailsPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SearchBtn = new javax.swing.JButton();
        TCode = new javax.swing.JComboBox();
        Date = new javax.swing.JComboBox();
        Month = new javax.swing.JComboBox();
        year = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        Month1 = new javax.swing.JComboBox();
        Date1 = new javax.swing.JComboBox();
        year1 = new javax.swing.JComboBox();
        ReportLBL = new javax.swing.JLabel();
        ContinueBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BookingDetailsPart2Panel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        AddressTF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        MaleRB = new javax.swing.JRadioButton();
        FemaleRB = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        AgeTF = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ArrivalTF = new javax.swing.JTextField();
        DepartureTF = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        AdvanceTF = new javax.swing.JTextField();
        RNoLBL = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        totalChargesLBL = new javax.swing.JLabel();
        BookBTN = new javax.swing.JButton();
        Stay = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EnterBookingDetailsPanel.setMaximumSize(new java.awt.Dimension(277, 200));
        EnterBookingDetailsPanel.setMinimumSize(new java.awt.Dimension(100, 100));
        EnterBookingDetailsPanel.setPreferredSize(new java.awt.Dimension(228, 200));

        jLabel2.setText("Room Type: ");

        jLabel3.setText("Arrival:");

        SearchBtn.setText("Search");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        TCode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Regular", "Family", "Deluxe", "Super Deluxe" }));

        Date.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        Month.setSelectedItem(01);
        Month.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MonthItemStateChanged(evt);
            }
        });

        year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2010", "2011", "2012" }));

        jLabel9.setText("Departure:");

        Month1.setSelectedItem(01);
        Month1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Month1ItemStateChanged(evt);
            }
        });

        Date1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        year1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2010", "2011", "2012" }));

        ReportLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReportLBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ContinueBtn.setText("Continue.. to Enter Details");
        ContinueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("ENTER BOOKING DETAILS");

        jLabel17.setText("MM");

        jLabel19.setText("DD");

        jLabel20.setText("YYYY");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("RAJ Guest House");

        javax.swing.GroupLayout EnterBookingDetailsPanelLayout = new javax.swing.GroupLayout(EnterBookingDetailsPanel);
        EnterBookingDetailsPanel.setLayout(EnterBookingDetailsPanelLayout);
        EnterBookingDetailsPanelLayout.setHorizontalGroup(
            EnterBookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EnterBookingDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ReportLBL, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EnterBookingDetailsPanelLayout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addComponent(SearchBtn)
                .addGap(158, 158, 158))
            .addGroup(EnterBookingDetailsPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(EnterBookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EnterBookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(EnterBookingDetailsPanelLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addGroup(EnterBookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EnterBookingDetailsPanelLayout.createSequentialGroup()
                                    .addComponent(TCode, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(56, 56, 56))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EnterBookingDetailsPanelLayout.createSequentialGroup()
                                    .addGroup(EnterBookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(EnterBookingDetailsPanelLayout.createSequentialGroup()
                                            .addGap(47, 47, 47)
                                            .addComponent(Month1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(EnterBookingDetailsPanelLayout.createSequentialGroup()
                                            .addComponent(jLabel19)
                                            .addGap(33, 33, 33)
                                            .addGroup(EnterBookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Month, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGap(19, 19, 19)
                                    .addGroup(EnterBookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel20)
                                        .addComponent(year1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(EnterBookingDetailsPanelLayout.createSequentialGroup()
                        .addGroup(EnterBookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EnterBookingDetailsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(Date1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(EnterBookingDetailsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)))
                        .addGap(234, 234, 234)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EnterBookingDetailsPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(ContinueBtn)
                .addGap(66, 66, 66))
            .addGroup(EnterBookingDetailsPanelLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        EnterBookingDetailsPanelLayout.setVerticalGroup(
            EnterBookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnterBookingDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(26, 26, 26)
                .addGroup(EnterBookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TCode, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(EnterBookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EnterBookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EnterBookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Date1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Month1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(SearchBtn)
                .addGap(13, 13, 13)
                .addComponent(ReportLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EnterBookingDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContinueBtn)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        BookingDetailsPart2Panel.setEnabled(false);

        jLabel8.setText("Room No.");

        jLabel10.setText("Name");

        jLabel11.setText("Address");

        jLabel12.setText("Sex");

        MaleRB.setText("Male");

        FemaleRB.setText("Female");

        jLabel13.setText("Age");

        jLabel14.setText("Arrival:");

        jLabel15.setText("Departure:");

        ArrivalTF.setEnabled(false);

        DepartureTF.setEnabled(false);

        jLabel16.setText("Advance");

        RNoLBL.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel18.setText("Charges: ");

        totalChargesLBL.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        BookBTN.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BookBTN.setText("BOOK");
        BookBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookBTNActionPerformed(evt);
            }
        });

        jLabel6.setText("No. of days");

        javax.swing.GroupLayout BookingDetailsPart2PanelLayout = new javax.swing.GroupLayout(BookingDetailsPart2Panel);
        BookingDetailsPart2Panel.setLayout(BookingDetailsPart2PanelLayout);
        BookingDetailsPart2PanelLayout.setHorizontalGroup(
            BookingDetailsPart2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingDetailsPart2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BookingDetailsPart2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookingDetailsPart2PanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(10, 10, 10)
                        .addComponent(RNoLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalChargesLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(BookingDetailsPart2PanelLayout.createSequentialGroup()
                        .addGroup(BookingDetailsPart2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(BookingDetailsPart2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BookingDetailsPart2PanelLayout.createSequentialGroup()
                                .addComponent(AddressTF, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(BookingDetailsPart2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(BookingDetailsPart2PanelLayout.createSequentialGroup()
                                    .addComponent(nameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                    .addGap(97, 97, 97))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookingDetailsPart2PanelLayout.createSequentialGroup()
                                    .addGroup(BookingDetailsPart2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BookingDetailsPart2PanelLayout.createSequentialGroup()
                                            .addComponent(MaleRB)
                                            .addGap(34, 34, 34)
                                            .addComponent(FemaleRB)
                                            .addGap(39, 39, 39)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                                        .addGroup(BookingDetailsPart2PanelLayout.createSequentialGroup()
                                            .addGroup(BookingDetailsPart2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(AgeTF, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(AdvanceTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                                .addComponent(DepartureTF, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(ArrivalTF, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                            .addGroup(BookingDetailsPart2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(BookBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Stay, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(37, 37, 37)))))))
        );
        BookingDetailsPart2PanelLayout.setVerticalGroup(
            BookingDetailsPart2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingDetailsPart2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BookingDetailsPart2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(BookingDetailsPart2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(RNoLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(totalChargesLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(BookingDetailsPart2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(BookingDetailsPart2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddressTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(BookingDetailsPart2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BookingDetailsPart2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(MaleRB)
                        .addComponent(FemaleRB))
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(BookingDetailsPart2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookingDetailsPart2PanelLayout.createSequentialGroup()
                        .addGroup(BookingDetailsPart2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AgeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(BookingDetailsPart2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ArrivalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(BookingDetailsPart2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DepartureTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(BookingDetailsPart2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AdvanceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookingDetailsPart2PanelLayout.createSequentialGroup()
                        .addComponent(Stay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(BookBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(EnterBookingDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(BookingDetailsPart2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(EnterBookingDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(BookingDetailsPart2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        // TODO add your handling code here:
        ReportLBL.setText("  ");
        boolean found = false;
        ContinueBtn.setVisible(false);
        int roomNo=0;
        int month = Integer.parseInt(Month.getSelectedItem().toString());
        aMonth=month;
        int month2 = Integer.parseInt(Month1.getSelectedItem().toString());
        dMonth=month2;
        int day1 = Integer.parseInt(Date.getSelectedItem().toString());
        aDay=day1;
        int day2 = Integer.parseInt(Date1.getSelectedItem().toString());
        dDay=day2;
        int y1 = Integer.parseInt(year.getSelectedItem().toString());
        aYear=y1;
        int y2 = Integer.parseInt(year1.getSelectedItem().toString());
        dYear=y2;
        char avail = 'n';
        String Tcode = TCode.getSelectedItem().toString();
        roomNo = search(month,month2,day1,day2,Tcode);
        if(roomNo ==0)
            ReportLBL.setText("No Room available.");
        else {
            ReportLBL.setText("Room No. " + roomNo + " is Available. Click continue to book the room.");
            ContinueBtn.setVisible(true);
            RNoLBL.setText(roomNo +"");
            ArrivalTF.setText(""+y1 +"/"+month + "/" + day1);
            DepartureTF.setText(""+y2 +"/"+month2 + "/" + day2);
        }
        Calendar c = Calendar.getInstance();
        c.set(y1,month,day1);
        Calendar c2 = Calendar.getInstance();
        c2.set(y2,month2,day2);
        stayTime = (int)((c2.getTimeInMillis() - c.getTimeInMillis())/(1000*60*60*24));
        Stay.setText(""+stayTime);
}//GEN-LAST:event_SearchBtnActionPerformed

    private void MonthItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MonthItemStateChanged
        // TODO add your handling code here:
        Date.removeAllItems();
        String m="0";
        int mon =0,days=0;
        int yr = Integer.parseInt(year.getSelectedItem().toString());
        if(Month.getSelectedIndex()>=1) {
            mon = Integer.parseInt(Month.getSelectedItem().toString());
        }
        if(mon==2)
            if(yr%4 != 0)
                days = 28;
            else
                days =29;
        else if( mon==4 || mon ==6 || mon==9 || mon==11)
            days = 30;
        else
            days = 31;
        for(int i =1; i<=days ;i++) {
            if(i>9)
                m="";
            Date.addItem(m+i);
        }
}//GEN-LAST:event_MonthItemStateChanged

    private void Month1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Month1ItemStateChanged
        Date1.removeAllItems();
        String m="0";
        int mon =0,days=0;
        int yr = Integer.parseInt(year1.getSelectedItem().toString());
        if(Month1.getSelectedIndex()>=1) {
            mon = Integer.parseInt(Month1.getSelectedItem().toString());
        }
        if(mon==2)
            if(yr%4 != 0)
                days = 28;
            else
                days =29;
        else if( mon==4 || mon ==6 || mon==9 || mon==11)
            days = 30;
        else
            days = 31;
        for(int i =1; i<=days ;i++) {
            if(i>9)
                m="";
            Date1.addItem(m+i);
        }
}//GEN-LAST:event_Month1ItemStateChanged

    private void ContinueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueBtnActionPerformed
        // TODO add your handling code here:
        String code = TCode.getSelectedItem().toString();
        try {
            Class.forName("java.sql.Driver");
            String database = "jdbc:mysql://localhost:3306/Hotal";
            Connection conn = DriverManager.getConnection(database, "root", "pace");
            Statement stmt = conn.createStatement();
            String sql = "select Charges from Type where TypeCode = '" + code + "'";
            ResultSet rs = stmt.executeQuery(sql);
            rs.next();
            int charge = rs.getInt("Charges");
            charge = charge * stayTime;
            totalChargesLBL.setText(charge+"");
            rs.close();
            stmt.close();
            conn.close();
        } catch (Exception e) { }
        EnterBookingDetailsPanel.setVisible(false);
        BookingDetailsPart2Panel.setVisible(true);
}//GEN-LAST:event_ContinueBtnActionPerformed

    private void BookBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookBTNActionPerformed
        // TODO add your handling code here:
        char gender = 'n';
        int month=aMonth;
        if(MaleRB.isSelected())
            gender = 'm';
        else if(FemaleRB.isSelected())
            gender = 'f';
        int age = Integer.parseInt(AgeTF.getText());
        int rno =Integer.parseInt(RNoLBL.getText());
        int advance =Integer.parseInt(AdvanceTF.getText());
        int tot =Integer.parseInt(totalChargesLBL.getText());
        try {
            Class.forName("java.sql.Driver");
            String database = "jdbc:mysql://localhost:3306/Hotal";
            Connection conn = DriverManager.getConnection(database, "root", "pace");
            Statement stmt2 = conn.createStatement();
            String sql2 = "Select max(BookingNo) from Booking";
            ResultSet rs = stmt2.executeQuery(sql2);
            rs.next();
            int bno = rs.getInt(1)+1;
            Statement stmt = conn.createStatement();
            String sql = "insert into Booking values (" + bno + ", '" + nameTF.getText() + "' , '" + AddressTF.getText() + "' , '" + gender + "' , "+ age + " , " + rno + " , '" + ArrivalTF.getText() + "' , '" + DepartureTF.getText() + "' , " + advance + " , " + tot + " )" ;
            stmt.executeUpdate(sql);
            while(month<=dMonth) {
                int max=getmax(month,dMonth,dDay);
                int min=0;
                if(month==aMonth)
                    min=aDay;
                else
                    min=1;
                for(int d=min;d<=max;d++) {
                    String sql3 = "update status" + month + " set D" + d + " = 'b' where RoomNo = " + rno;
                    stmt.executeUpdate(sql3);
                }
                month++;
            }
            JOptionPane.showMessageDialog(null,"Room booked. Booking number is: "+ bno);
            stmt.close();
            stmt2.close();
            conn.close();
            new ReservaTionSlip(bno).setVisible(true);
            this.setVisible(false);
        } catch (Exception e) { JOptionPane.showMessageDialog(null,"Invalid Data" + e); }
}//GEN-LAST:event_BookBTNActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
 private int getmax(int month1 ,int month2, int d2)
    {
        if(month1 == month2)
            return d2;
        else if(month1 == 2)
            return 28;
        else if(month1==4 || month1==6 || month1==9 || month1==11)
            return 30;
        else
            return 31;
    }
    private int search(int month, int month2, int day1, int day2, String Tcode)
    {
        String avail="f";
        boolean found = false;
        int rNo = 0;
        int max = getmax(month,month2,day2);
        try {
            Class.forName("java.sql.Driver");
            String database = "jdbc:mysql://localhost:3306/Hotal";
            Connection conn = DriverManager.getConnection(database, "root", "pace");
            Statement stmt = conn.createStatement();
            String sql = "select * from Status" + month + " where TypeCode = '" + Tcode + "'";
            ResultSet rs = stmt.executeQuery(sql);
            while(rs.next())
            {
               int i;
               for(i=day1; i<=max; i++)
               {
                   avail = rs.getString(i+2);

                   if (avail.equals("b") || avail.equals("o"))
                       break;
               }
               if(i == max+1)
               {
                   rNo = rs.getInt(1);
                   if(month != month2)
                    found = search2(month+1,month2,1,day2,Tcode,rNo);
                   else
                       break;
                    if(found)
                       break;
               }
           }
           rs.close();
           stmt.close();
           conn.close();
        } catch (Exception e) { ReportLBL.setText("Incorrect Entry" + e);}
        return rNo;
    }
    private boolean search2(int month1 , int month2,int day1,int day2, String Tcode , int rno)
    {
        String avail="f";
        boolean found = false;
        int rNo = 0;
        int max = getmax(month1,month2,day2);
        try {
            Class.forName("java.sql.Driver");
            String database = "jdbc:mysql://localhost:3306/Hotal";
            Connection conn = DriverManager.getConnection(database, "root", "pace");
            Statement stmt = conn.createStatement();
            String sql = "select * from status" + month1 + " where TypeCode = '" + Tcode + "' and RoomNo = " + rno;
            ResultSet rs = stmt.executeQuery(sql);
            rs.next();
               int i;
               for(i=day1; i<=max; i++)
               {
                   avail = rs.getString(i+2);
                   if (avail.equals("b") || avail.equals("o"))
                       break;
               }
               if(i == max+1)
               {
                   if(month1 != month2)
                    found = search2(month1+1,month2,1,day2,Tcode,rNo);
                   else
                       return true;
               }
               rs.close();
               stmt.close();
               conn.close();
        } catch (Exception e) { ReportLBL.setText("Incorrect Entry");}
        return found;
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressTF;
    private javax.swing.JTextField AdvanceTF;
    private javax.swing.JTextField AgeTF;
    private javax.swing.JTextField ArrivalTF;
    private javax.swing.JButton BookBTN;
    private javax.swing.JPanel BookingDetailsPart2Panel;
    private javax.swing.JButton ContinueBtn;
    private javax.swing.JComboBox Date;
    private javax.swing.JComboBox Date1;
    private javax.swing.JTextField DepartureTF;
    private javax.swing.JPanel EnterBookingDetailsPanel;
    private javax.swing.JRadioButton FemaleRB;
    private javax.swing.JRadioButton MaleRB;
    private javax.swing.JComboBox Month;
    private javax.swing.JComboBox Month1;
    private javax.swing.JLabel RNoLBL;
    private javax.swing.JLabel ReportLBL;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JLabel Stay;
    private javax.swing.JComboBox TCode;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel totalChargesLBL;
    private javax.swing.JComboBox year;
    private javax.swing.JComboBox year1;
    // End of variables declaration//GEN-END:variables

}
