
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ReservationSlipGenration.java
 *
 * Created on Jan 25, 2011, 11:47:05 PM
 */

/**
 *
 * @author Administrator
 */
public class ReservationSlipGenration extends javax.swing.JFrame {

    /** Creates new form ReservationSlipGenration */
    public ReservationSlipGenration() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ResSlipPanel = new javax.swing.JPanel();
        GenerateResSlipBTN = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        BokingNo4ResSlipTF = new javax.swing.JTextField();
        error1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ResSlipPanel.setMaximumSize(new java.awt.Dimension(367, 367));
        ResSlipPanel.setPreferredSize(new java.awt.Dimension(87, 104));

        GenerateResSlipBTN.setText("Get Reservation Slip");
        GenerateResSlipBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateResSlipBTNActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16));
        jLabel4.setText("ENTER BOOKING NUMBER");

        BokingNo4ResSlipTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BokingNo4ResSlipTFActionPerformed(evt);
            }
        });

        error1.setText("           ");
        error1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16));
        jLabel7.setText("TO GENERATE RESERVATION SLIP");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("RAJ Guest House");

        javax.swing.GroupLayout ResSlipPanelLayout = new javax.swing.GroupLayout(ResSlipPanel);
        ResSlipPanel.setLayout(ResSlipPanelLayout);
        ResSlipPanelLayout.setHorizontalGroup(
            ResSlipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResSlipPanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel7)
                .addGap(57, 57, 57))
            .addGroup(ResSlipPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(error1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(ResSlipPanelLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(BokingNo4ResSlipTF, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
            .addGroup(ResSlipPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(GenerateResSlipBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addGap(66, 66, 66)
                .addComponent(jButton1)
                .addGap(76, 76, 76))
            .addGroup(ResSlipPanelLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(ResSlipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ResSlipPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(ResSlipPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                        .addGap(85, 85, 85))))
        );
        ResSlipPanelLayout.setVerticalGroup(
            ResSlipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResSlipPanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(36, 36, 36)
                .addComponent(BokingNo4ResSlipTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(ResSlipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenerateResSlipBTN)
                    .addComponent(jButton1))
                .addGap(34, 34, 34)
                .addComponent(error1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ResSlipPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ResSlipPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GenerateResSlipBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateResSlipBTNActionPerformed
        // TODO add your handling code here:
        int bno = Integer.parseInt( BokingNo4ResSlipTF.getText());
        if(search(bno)) {
            new ReservaTionSlip(bno).setVisible(true);
            this.setVisible(false);
        } else {
            error1.setText("Unable to fine Booking number");
        }
}//GEN-LAST:event_GenerateResSlipBTNActionPerformed
private boolean search(int bno)
{
     try {
            Class.forName("java.sql.Driver");
            String database = "jdbc:mysql://localhost:3306/Hotal";
            Connection conn = DriverManager.getConnection(database, "root", "pace");
            Statement stmt = conn.createStatement();
            String sql = "select * from Booking where BookingNo = " + bno;
            ResultSet rs = stmt.executeQuery(sql);
            if(rs.next())
            {
               return true;
            }
            else
            {
                return false;
            }
        } catch (Exception e) { JOptionPane.showMessageDialog(null,"" + e);
        return false; }
}
    private void BokingNo4ResSlipTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BokingNo4ResSlipTFActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_BokingNo4ResSlipTFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservationSlipGenration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BokingNo4ResSlipTF;
    private javax.swing.JButton GenerateResSlipBTN;
    private javax.swing.JPanel ResSlipPanel;
    private javax.swing.JLabel error1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables

}
